//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaMatricula.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aluno
    {
        public int id { get; set; }
        public int turma_id { get; set; }
        public int endereco_id { get; set; }
        public int contato_id { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 3 e no máximo 60 caracteres", MinimumLength = 3)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string nomeAluno { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 4 e no máximo 60 caracteres", MinimumLength = 4)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string nomeResponsavel { get; set; }


        [StringLength(14, ErrorMessage = "CPF deve conter 11 dígitos", MinimumLength = 14)]
        [ValidaCpf]
        [Required(ErrorMessage = "Campo Necessário")]
        public string cpfAluno { get; set; }


        [StringLength(14, ErrorMessage = "CPF deve conter 11 dígitos", MinimumLength = 14)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string cpfResponsavel { get; set; }


        [Required(ErrorMessage = "Campo Necessário")]
        public string sexo { get; set; }


        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Campo Necessário")]
        public System.DateTime dataNascimento { get; set; }


        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Required(ErrorMessage = "Campo Necessário")]
        public System.DateTime dataMatricula { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> dataSaida { get; set; }


        [StringLength(11, ErrorMessage = "Mínimo 2 e no máximo 11 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string matricula { get; set; }


        [StringLength(100, ErrorMessage = "Mínimo 1 e no máximo 100 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string beneficios { get; set; }


        [StringLength(100, ErrorMessage = "Mínimo 1 e no máximo 100 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string restricoes { get; set; }
        public bool situacao { get; set; }

        public virtual contato contato { get; set; }
        public virtual endereco endereco { get; set; }
        public virtual turma turma { get; set; }

    }
}
