//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaMatricula.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class contato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contato()
        {
            this.aluno = new HashSet<aluno>();
        }
    
        public int id { get; set; }


        [StringLength(12, ErrorMessage = "Mínimo 2 e no máximo 12 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string fone1 { get; set; }

        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string contato1 { get; set; }

        [StringLength(12, ErrorMessage = "Mínimo 2 e no máximo 612 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string fone2 { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string contato2 { get; set; }

        [StringLength(12, ErrorMessage = "Mínimo 2 e no máximo 12 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string fone3 { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string contato3 { get; set; }

        [StringLength(12, ErrorMessage = "Mínimo 2 e no máximo 12 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string fone4 { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string contato4 { get; set; }

        [StringLength(12, ErrorMessage = "Mínimo 2 e no máximo 12 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string fone5 { get; set; }


        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string contato5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno> aluno { get; set; }
    }
}
