//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaMatricula.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class disciplina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplina()
        {
            this.turma = new HashSet<turma>();
        }
    
        public int id { get; set; }
        [StringLength(40, ErrorMessage = "Informe ao menos 4 caracteres e no máximo 40", MinimumLength = 4)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string nome { get; set; }
        [StringLength(60, ErrorMessage = "Limite de 60 caracteres ultrapassado", MinimumLength = 0)]
        public string descricao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turma> turma { get; set; }
    }
}
