//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemaMatricula.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public endereco()
        {
            this.aluno = new HashSet<aluno>();
        }
    
        public int id { get; set; }

        [StringLength(10, ErrorMessage = "Mínimo 8 e no máximo 10 caracteres", MinimumLength = 8)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string cep { get; set; }

        [StringLength(60, ErrorMessage = "Mínimo 2 e no máximo 60 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string descricao { get; set; }

        [StringLength(10, ErrorMessage = "Mínimo 2 e no máximo 10 caracteres", MinimumLength = 2)]
        [Required(ErrorMessage = "Campo Necessário")]
        public string numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno> aluno { get; set; }
    }
}
